/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicoHerenciaInstitutoInterfaz;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import practicoHerenciaInstituto.Instituto;
import practicoHerenciaInstituto.Estudiante;
import practicoHerenciaInstituto.Docente;
import practicoHerenciaInstituto.Administrativo;
/**
 *
 * @author 57815971
 */
public class SeleccionInstituto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeleccionInstituto.class.getName());
    private Instituto instituto;
    private DefaultListModel modeloEst;
    private DefaultListModel modeloProf;
    private DefaultListModel modeloAdmin;
    
    /**
     * Creates new form SeleccionInstituto
     */
    public SeleccionInstituto(Instituto i) {
        initComponents();
        this.instituto = i;
        lblInstituto.setText(instituto.getNombre());
        modeloEst = new DefaultListModel();
        for (Estudiante e : instituto.getListaEstudiantes()){
            int ci = e.getCedula();
        }
        jListEstudiantes.setModel(modeloEst);
        
        modeloProf = new DefaultListModel();
        jListProfesores.setModel(modeloProf);
        
        modeloAdmin = new DefaultListModel();
        jListAdministrativos.setModel(modeloAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        lblInstituto = new javax.swing.JLabel();
        btnSeleccionarProf = new javax.swing.JButton();
        btnSeleccionarEst = new javax.swing.JButton();
        btnSeleccionarAdmin = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEstHabilidados = new javax.swing.JButton();
        btnProfDedicados = new javax.swing.JButton();
        btnCierreNocturno = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAdministrativos = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListProfesores = new javax.swing.JList<>();

        jScrollPane4.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstituto.setText("Nombre");

        btnSeleccionarProf.setText("jButton1");

        btnSeleccionarEst.setText("jButton2");

        btnSeleccionarAdmin.setText("jButton3");

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Instituto:");

        jLabel3.setText("jLabel3");

        btnEstHabilidados.setText("habilitado");
        btnEstHabilidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstHabilidadosActionPerformed(evt);
            }
        });

        btnProfDedicados.setText("alta dedicaicon");
        btnProfDedicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfDedicadosActionPerformed(evt);
            }
        });

        btnCierreNocturno.setText("cierre");
        btnCierreNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreNocturnoActionPerformed(evt);
            }
        });

        jListEstudiantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jListEstudiantes);

        jListAdministrativos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(jListAdministrativos);

        jListProfesores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(jListProfesores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnEstHabilidados)
                .addGap(18, 18, 18)
                .addComponent(btnProfDedicados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCierreNocturno)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(lblInstituto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnSeleccionarEst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionarProf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(btnSeleccionarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnSeleccionarProf))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnVolver)
                                    .addComponent(jLabel1)
                                    .addComponent(lblInstituto))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(btnSeleccionarEst))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(btnSeleccionarAdmin))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstHabilidados)
                    .addComponent(btnProfDedicados)
                    .addComponent(btnCierreNocturno))
                .addGap(21, 21, 21))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCierreNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreNocturnoActionPerformed
    JOptionPane.showMessageDialog(this, instituto.cierreNocturno());

    }//GEN-LAST:event_btnCierreNocturnoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Institutos institutos = new Institutos();
        institutos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEstHabilidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstHabilidadosActionPerformed
        JOptionPane.showMessageDialog(this, instituto.alumnosHabilitados());
    }//GEN-LAST:event_btnEstHabilidadosActionPerformed

    private void btnProfDedicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfDedicadosActionPerformed
    JOptionPane.showMessageDialog(this, instituto.docentesAltaDedicacion());
    }//GEN-LAST:event_btnProfDedicadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Instituto i = new Instituto("");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SeleccionInstituto(i).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCierreNocturno;
    private javax.swing.JButton btnEstHabilidados;
    private javax.swing.JButton btnProfDedicados;
    private javax.swing.JButton btnSeleccionarAdmin;
    private javax.swing.JButton btnSeleccionarEst;
    private javax.swing.JButton btnSeleccionarProf;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListAdministrativos;
    private javax.swing.JList<String> jListEstudiantes;
    private javax.swing.JList<String> jListProfesores;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblInstituto;
    // End of variables declaration//GEN-END:variables
}
