/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicoHerenciaInstitutoInterfaz;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import practicoHerenciaInstitutoLogica.Instituto;
import practicoHerenciaInstitutoLogica.Estudiante;
import practicoHerenciaInstitutoLogica.Docente;
import practicoHerenciaInstitutoLogica.Administrativo;
/**
 *
 * @author 57815971
 */
public class SeleccionInstituto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SeleccionInstituto.class.getName());
    private Instituto instituto;
    private DefaultListModel modeloEst;
    private DefaultListModel modeloDoc;
    private DefaultListModel modeloAdmin;
    
    //FALTAN LOS BOTODES DE EDITAR PERSONA, PERO TENGO QUE VER SI PUEDO HACER HERENCIA DE UNA VENTANA DE ESTA PORUQE SNO TODOS IGUALES (casi)
    //METODO PARA PEDIR LOS DATOS DE TODOS
    /**
     * Creates new form SeleccionInstituto
     */
    public SeleccionInstituto(Instituto i) {
        initComponents();
        this.instituto = i;
        lblInstituto.setText(instituto.getNombre());
        
        modeloEst = new DefaultListModel();
        jListEstudiantes.setModel(modeloEst);
        for (Estudiante e : instituto.getListaEstudiantes()){
            int ci = e.getCedula();
            String apellido = e.getApellido();
            String nombre = e.getNombre();
            String estudiante = ci+", "+apellido+" "+nombre;
            modeloEst.addElement(estudiante);
        }
        
        modeloDoc = new DefaultListModel();
        jListDocentes.setModel(modeloDoc);
        for (Docente d : instituto.getListaDocentes()){
            int ci = d.getCedula();
            String apellido = d.getApellido();
            String nombre = d.getNombre();
            String docente = ci+", "+apellido+" "+nombre;
            modeloDoc.addElement(docente);
        }
        
        modeloAdmin = new DefaultListModel();
        jListAdministrativos.setModel(modeloAdmin);
        for (Administrativo a : instituto.getListaAdministrativos()){
            int ci = a.getCedula();
            String apellido = a.getApellido();
            String nombre = a.getNombre();
            String administrativo = ci+", "+apellido+" "+nombre;
            modeloAdmin.addElement(administrativo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        lblInstituto = new javax.swing.JLabel();
        btnSeleccionarDoc = new javax.swing.JButton();
        btnSeleccionarEst = new javax.swing.JButton();
        btnSeleccionarAdmin = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEstHabilidados = new javax.swing.JButton();
        btnProfDedicados = new javax.swing.JButton();
        btnCierreNocturno = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListEstudiantes = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jListAdministrativos = new javax.swing.JList<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        jListDocentes = new javax.swing.JList<>();
        btnAgregarEst = new javax.swing.JButton();
        btnAgregarDoc = new javax.swing.JButton();
        btnAgregarAdmin = new javax.swing.JButton();

        jScrollPane4.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInstituto.setText("Nombre");

        btnSeleccionarDoc.setText("Seleccionar");
        btnSeleccionarDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarDocActionPerformed(evt);
            }
        });

        btnSeleccionarEst.setText("Seleccionar");
        btnSeleccionarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarEstActionPerformed(evt);
            }
        });

        btnSeleccionarAdmin.setText("Seleccionar");
        btnSeleccionarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarAdminActionPerformed(evt);
            }
        });

        btnVolver.setText("volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Instituto:");

        jLabel3.setText("jLabel3");

        btnEstHabilidados.setText("habilitado");
        btnEstHabilidados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstHabilidadosActionPerformed(evt);
            }
        });

        btnProfDedicados.setText("alta dedicaicon");
        btnProfDedicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfDedicadosActionPerformed(evt);
            }
        });

        btnCierreNocturno.setText("cierre");
        btnCierreNocturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreNocturnoActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(jListEstudiantes);

        jScrollPane6.setViewportView(jListAdministrativos);

        jScrollPane7.setViewportView(jListDocentes);

        btnAgregarEst.setText("+");
        btnAgregarEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEstActionPerformed(evt);
            }
        });

        btnAgregarDoc.setText("+");

        btnAgregarAdmin.setText("+");
        btnAgregarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnAgregarEst)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregarDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btnAgregarAdmin))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(139, 139, 139)
                            .addComponent(btnSeleccionarDoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnVolver)
                            .addGap(42, 42, 42)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(lblInstituto))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(405, 405, 405))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnEstHabilidados)
                        .addGap(18, 18, 18)
                        .addComponent(btnProfDedicados)
                        .addGap(32, 32, 32)
                        .addComponent(btnCierreNocturno))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSeleccionarEst)
                        .addGap(169, 169, 169)
                        .addComponent(btnSeleccionarAdmin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver)
                            .addComponent(jLabel1)
                            .addComponent(lblInstituto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionarDoc)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(btnAgregarDoc))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnSeleccionarEst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSeleccionarAdmin)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(btnAgregarEst)
                                                .addGap(34, 34, 34)
                                                .addComponent(jLabel3))
                                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(btnAgregarAdmin)))))
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstHabilidados)
                    .addComponent(btnProfDedicados)
                    .addComponent(btnCierreNocturno))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCierreNocturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreNocturnoActionPerformed
    JOptionPane.showMessageDialog(this, instituto.cierreNocturno());

    }//GEN-LAST:event_btnCierreNocturnoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ManipularInstitutos institutos = new ManipularInstitutos();
        institutos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnEstHabilidadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstHabilidadosActionPerformed
        JOptionPane.showMessageDialog(this, instituto.alumnosHabilitados());
    }//GEN-LAST:event_btnEstHabilidadosActionPerformed

    private void btnProfDedicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfDedicadosActionPerformed
    JOptionPane.showMessageDialog(this, instituto.docentesAltaDedicacion());
    }//GEN-LAST:event_btnProfDedicadosActionPerformed

    private void btnSeleccionarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarAdminActionPerformed

    private void btnSeleccionarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarEstActionPerformed
        
    }//GEN-LAST:event_btnSeleccionarEstActionPerformed

    private void btnAgregarEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEstActionPerformed
        IngresarEstudiante ingresarEstudiante = new IngresarEstudiante(instituto);
        ingresarEstudiante.setVisible(true);
 
        Estudiante e = instituto.getListaEstudiantes().getLast();
        int ci = e.getCedula();
        String apellido = e.getApellido();
        String nombre = e.getNombre();
        String estudiante = ci+", "+apellido+" "+nombre;
        modeloEst.addElement(estudiante);
    }//GEN-LAST:event_btnAgregarEstActionPerformed

    private void btnAgregarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarAdminActionPerformed

    private void btnSeleccionarDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeleccionarDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Instituto i = new Instituto("");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SeleccionInstituto(i).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAdmin;
    private javax.swing.JButton btnAgregarDoc;
    private javax.swing.JButton btnAgregarEst;
    private javax.swing.JButton btnCierreNocturno;
    private javax.swing.JButton btnEstHabilidados;
    private javax.swing.JButton btnProfDedicados;
    private javax.swing.JButton btnSeleccionarAdmin;
    private javax.swing.JButton btnSeleccionarDoc;
    private javax.swing.JButton btnSeleccionarEst;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListAdministrativos;
    private javax.swing.JList<String> jListDocentes;
    private javax.swing.JList<String> jListEstudiantes;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lblInstituto;
    // End of variables declaration//GEN-END:variables
}
